"""
Physically-inspired tone generator for the five instruments Just Piano offers.

Every note is synthesised offline (once, then disk-cached) from a modal model:
a set of decaying sinusoids whose frequencies, levels and decay rates come from
the mechanics of the instrument that is being imitated. Nothing here is a
recording -- there is no sample library to download, and the .app carries no
audio at all.

Two families share one summation kernel (`_sum_partials`), because the arithmetic
of "add up a few hundred exponentially decaying, slightly detuned sinusoids" is
the same either way; what differs is where the numbers come from.

**Struck strings** (`grand`, `upright`, `felt`) -- a string plus the soundboard
that radiates it:

  * inharmonic partial series      f_n = n*f0*sqrt(1 + B*n^2), B spanning
                                   ~3e-5 (A0) to ~3e-2 (C8), scaled per voicing
                                   (an upright's short bass strings are far more
                                   inharmonic than a concert grand's)
  * measured spectral envelope     -6 dB/octave (grand) over the partial series
  * soundboard radiation           modal peaks near 50/80/120 Hz and a 12
                                   dB/octave roll-off below a per-voicing corner,
                                   so the bass fundamental is 10-20 dB *weaker*
                                   than partials 2-4, as on a real instrument
  * hammer strike-position comb    |sin(pi*n*p)|, p ~ 1/7 in the mid range,
                                   which is why the 7th partial is weak
  * per-partial two-stage decay    T60 ~ 1/f, knee at -25 dB, stage-2 T60 3x
                                   stage-1 (vertical->horizontal polarisation)
  * true unison choirs             1 string A0-E1, 2 up to B2, 3 above, all
                                   sharing one launch phase, detuned 0.5-2 ct
  * stretch tuning                 octave widening derived from the model's own
                                   inharmonicity, so partial 2 of a key lands on
                                   partial 1 of the key an octave up. Nearly all
                                   of it is treble (C8 ends ~42 cents sharp of
                                   equal temperament); A4 sounds at 440.000
  * mechanical noise               hammer strike, key-bed thump, damper lift,
                                   all rung through the body

**Struck bars behind a pickup** (`rhodes`, `wurlitzer`) -- an electric piano is
not a string instrument and modelling it as one is why most synthesised Rhodes
patches sound like a filtered organ. What is actually vibrating is a stiff
cantilever, and what you hear is a pickup's non-linear view of it:

  * bending modes, not harmonics   a clamped-free bar rings at 1 : 6.27 : 17.55 :
                                   34.4 -- wildly inharmonic. Those upper modes
                                   are the "tine bark", they are what a DX7
                                   E.PIANO patch is imitating with a modulator at
                                   ratio 18, and they die in a few hundred ms
                                   while the fundamental sings on.
  * a harmonic series on top       generated by the pickup, not by the bar: the
                                   magnetic (Rhodes) or electrostatic (Wurlitzer)
                                   transfer is non-linear, so a nearly sinusoidal
                                   motion comes out with harmonics. Harmonic n
                                   grows as the n-th power of the excursion and
                                   therefore decays n times faster -- which the
                                   T60 ~ 1/f law reproduces for free, and which is
                                   why an electric piano *purifies* as it decays.
  * a tuned partner               the Rhodes tine is one arm of an asymmetric fork
                                   (tine + tonebar); the pair beats slowly. The
                                   Wurlitzer's lead-loaded reed beats far less.
  * a pickup non-linearity        an asymmetric (even-harmonic) term for the way
                                   the field falls off across the swing, then a
                                   symmetric saturation for the overdrive. The
                                   Wurlitzer's electrostatic pickup runs at 170 V
                                   across a tiny gap and is the more violent of
                                   the two: that is the famous "bark".

Two velocity layers ("soft" / "hard") are rendered per note and cross-faded at
play time, so timbre gets brighter as you hit harder -- not just louder. Both
layers share the same random phases so the cross-fade is a clean spectral morph
rather than a chorus-y phase mush.
"""

from __future__ import annotations

import hashlib
import math

import numpy as np

SAMPLE_RATE = 44100

# Generation marker of the tone model, used by `samplebank` to invalidate a
# stale on-disk cache. Bump it by hand on *any* change to `render_note`,
# `note_duration`, `inharmonicity`, `VOICINGS` or `_LAYER_PARAMS`: the sample
# cache cannot tell otherwise (source hashing is unavailable inside the
# packaged .app).
#   "2": partial series cut at a frequency instead of a partial index.
#   "3": string + soundboard model, per-partial decay, unison choirs, voicings.
#   "4": felt's action layer trimmed 10 dB (`action_db`), so the tone leads it.
#   "5": five voicings in two families -- `warm` became `upright` (its own
#        inharmonicity, board and action), and the tine/reed engine behind
#        `rhodes` and `wurlitzer` arrived.
#   "6": stretch tuning -- the struck-string voicings are no longer tuned
#        to equal temperament (see `stretch_cents`).
TONE_MODEL_REVISION = "6"

NOTE_MIN = 21   # A0
NOTE_MAX = 108  # C8

LAYERS = ("soft", "hard")

#: The two synthesis engines. A voicing names one in its `family` key.
STRING = "string"       # struck string + soundboard
ELECTRIC = "electric"   # struck bar + pickup

DEFAULT_VOICING = "grand"


# --------------------------------------------------------------------- voicings
#: Knobs every voicing has, whatever family it is in. A voicing literal below
#: only spells out what it changes; `_merge_voicings` fills in the rest, so a
#: lookup can never raise for a key one family happens not to care about.
#:
#:   family       : STRING or ELECTRIC -- which engine renders it
#:   tone_gain    : level of the whole vibrating-object sound. The mechanical
#:                  noise is quoted at an absolute level, so a voicing that turns
#:                  its tone down gets its action noise pushed up the mix; use
#:                  `action_db` to trim it back to where it belongs.
#:   action_db    : dB trim of the whole mechanical-noise layer. Velocity still
#:                  scales the noise within it, so this moves the balance without
#:                  flattening the dynamics.
#:   tilt_db_oct  : fall-off of the partial series, dB per octave of partial
#:                  index, measured at ff (grands sit around -6)
#:   hf_corner_hz : where an extra high-frequency roll-off sets in
#:   hf_db_oct    : that extra roll-off, dB/octave (adds to tilt_db_oct)
#:   t60_ref_s    : stage-1 T60 of a 261.6 Hz partial (mid range: 5-10 s)
#:   t60_slope    : exponent of the T60 ~ (f_ref/f)**slope law (1.0 = pure 1/f)
#:   t60_max_s    : ceiling on any one partial's T60
#:   hf_damp      : how much faster partials above hf_corner_hz die (exponent)
#:   attack_ms    : time constant of the contact attack
#:   dur_bass_s   : rendered buffer length at A0 ...
#:   dur_treble_s : ... and at C8; every key in between is interpolated
#:                  geometrically (see `note_duration`)
#:   gain         : playback make-up gain (see `note_gain`)
_COMMON_DEFAULTS: dict[str, object] = dict(
    family=STRING,
    tone_gain=1.00, action_db=0.0,
    tilt_db_oct=-6.0, hf_corner_hz=5000.0, hf_db_oct=-6.0,
    t60_ref_s=7.5, t60_slope=1.0, t60_max_s=20.0, hf_damp=0.15,
    attack_ms=2.2, dur_bass_s=8.0, dur_treble_s=0.70, gain=1.00,
)

#: Knobs only the struck-string engine reads.
#:   fund_db        : emphasis of the fundamental over the overtone series
#:   board_low/mid  : soundboard modal gains (low = 50/80/120 Hz, mid = wood)
#:   body_mix       : how much of the body's ringing impulse response is added
#:   rad_corner_hz  : below this the board radiates ever worse, 12 dB/octave.
#:                    A small upright board gives up higher than a concert grand.
#:   inharm_bass    : multiplier on the measured inharmonicity B at A0 ...
#:   inharm_treble  : ... and at C8 (an upright's bass strings are cruelly short)
#:   strike_scale   : multiplier on the hammer's contact point along the string
#:   stretch        : depth of the tuning curve (`stretch_cents`), 1.0 = the
#:                    reference grand. A shorter, more inharmonic instrument
#:                    is tuned further from equal temperament, not less.
_STRING_DEFAULTS: dict[str, object] = dict(
    fund_db=0.0, board_low=1.0, board_mid=1.0, body_mix=0.45,
    rad_corner_hz=200.0, inharm_bass=1.0, inharm_treble=1.0, strike_scale=1.0,
    stretch=1.0,
)

#: Knobs only the bar-and-pickup engine reads.
#:   odd_db/even_db : level trim of the odd / even harmonics the pickup makes.
#:                    A Rhodes reads as a sine with a bell on it; a Wurlitzer is
#:                    "closer to a sawtooth", hollow and odd-harmonic-led.
#:   bar_ratios     : bending-mode frequencies as multiples of the fundamental.
#:                    A clamped-free bar gives 6.267/17.55/34.39; a mass at the
#:                    tip (the Wurlitzer's lead blob) pulls them down and in.
#:   bar_db         : level of the first bending mode at ff, against the
#:                    fundamental ...
#:   bar_tilt_db    : ... and how much weaker each further one is
#:   bar_t60_s      : T60 of a 1 kHz bending mode -- these are the transient
#:   bar_vel_exp    : exponent of their velocity law. High: the bell is what a
#:                    hard blow adds, and a whisper is nearly a pure sine.
#:   bar_detune_ct  : scatter on the mode frequencies, cents
#:   beat_ct        : detuning of the tuned partner (tonebar / reed damper) ...
#:   beat_gain      : ... and its level, which sets how deep the beat swings
#:   pickup_asym    : strength of the even-harmonic (asymmetric) pickup term
#:   pickup_drive   : strength of the symmetric saturation on top of it
#:   hf_taps        : passes of a gentle 3-tap smoother standing in for the
#:                    pickup's and preamp's top-end loss
#:   knock_db       : hammer tip on the bar, and the key bed under it
_ELECTRIC_DEFAULTS: dict[str, object] = dict(
    odd_db=0.0, even_db=0.0, bar_ratios=(6.267, 17.55, 34.39),
    bar_db=-9.0, bar_tilt_db=-7.0, bar_t60_s=0.40, bar_vel_exp=2.4,
    bar_detune_ct=8.0, beat_ct=1.6, beat_gain=0.30,
    pickup_asym=0.30, pickup_drive=0.30, hf_taps=1, knock_db=-28.0,
)

_VOICING_SPECS: dict[str, dict[str, object]] = {
    # ------------------------------------------------------------ struck strings
    "grand": dict(family=STRING),          # the reference: every default above
    # An upright is not a quiet grand, it is a shorter one. Its bass strings are
    # cut to fit the case, which multiplies their inharmonicity (that clangy,
    # fundamental-poor bottom octave); its board is small, so it gives up
    # radiating an octave higher and leans on the midrange instead; and its
    # action -- the hammers return by spring, not by gravity -- is audibly busier.
    "upright": dict(
        family=STRING,
        tilt_db_oct=-6.8, hf_corner_hz=4200.0, hf_db_oct=-7.5,
        fund_db=1.5, t60_ref_s=5.6, hf_damp=0.30, attack_ms=2.6,
        tone_gain=0.92, action_db=3.0,
        board_low=0.78, board_mid=1.32, body_mix=0.60, rad_corner_hz=300.0,
        inharm_bass=3.2, inharm_treble=1.25, strike_scale=0.94,
        dur_bass_s=6.0, dur_treble_s=0.62, gain=1.06),
    # Felt: a moderator strip between hammer and string. The strings come down
    # ~13 dB and go dark, which leaves the action unusually audible -- roughly
    # 4 dB above where the grand carries it, relative to the strings -- but
    # trimmed 10 dB from its absolute level so the tone still leads and the
    # voicing reads soft and intimate rather than clicky.
    "felt": dict(
        family=STRING,
        tilt_db_oct=-6.5, hf_corner_hz=1600.0, hf_db_oct=-15.0,
        fund_db=8.0, t60_ref_s=5.5, hf_damp=0.70, attack_ms=8.5,
        tone_gain=0.22, action_db=-10.0,
        board_low=1.10, board_mid=1.45, body_mix=0.75,
        dur_bass_s=6.8, dur_treble_s=0.595, gain=1.20),

    # ------------------------------------------------------- struck bars/pickups
    # Rhodes: a tine struck by a neoprene tip, its tonebar beating slowly against
    # it, read by a magnetic pickup. Nearly a sine once the bell has gone, so the
    # harmonic series is steep; the bark lives entirely in the bending modes and
    # only a hard blow brings it out.
    "rhodes": dict(
        family=ELECTRIC,
        tilt_db_oct=-15.5, hf_corner_hz=2600.0, hf_db_oct=-9.0,
        odd_db=0.0, even_db=-3.5,
        t60_ref_s=9.0, t60_slope=1.0, t60_max_s=12.0, hf_damp=0.55,
        attack_ms=1.6,
        bar_ratios=(6.267, 17.55, 34.39), bar_db=-8.5, bar_tilt_db=-7.5,
        bar_t60_s=0.45, bar_vel_exp=2.4, bar_detune_ct=9.0,
        beat_ct=1.8, beat_gain=0.32,
        pickup_asym=0.34, pickup_drive=0.22, hf_taps=1,
        knock_db=-30.0, action_db=0.0,
        dur_bass_s=7.5, dur_treble_s=1.00, gain=1.10),
    # Wurlitzer: a flat steel reed with a lead blob on the tip, swinging inside
    # an electrostatic pickup at 170 V. Far richer than a Rhodes ("closer to a
    # sawtooth"), hollow because the odd harmonics lead, much shorter in the
    # sustain, and it barks: the capacitance of that tiny gap goes as 1/(gap - x),
    # so a hard blow drives real saturation rather than a bell.
    "wurlitzer": dict(
        family=ELECTRIC,
        tilt_db_oct=-9.5, hf_corner_hz=3400.0, hf_db_oct=-11.0,
        odd_db=3.5, even_db=-4.5,
        t60_ref_s=4.2, t60_slope=0.78, t60_max_s=6.5, hf_damp=0.45,
        attack_ms=1.1,
        bar_ratios=(4.60, 12.40, 24.00), bar_db=-15.0, bar_tilt_db=-9.0,
        bar_t60_s=0.20, bar_vel_exp=2.0, bar_detune_ct=14.0,
        beat_ct=0.7, beat_gain=0.16,
        pickup_asym=0.24, pickup_drive=0.95, hf_taps=2,
        knock_db=-23.0, action_db=2.0,
        dur_bass_s=4.6, dur_treble_s=0.80, gain=1.14),
}


def _merge_voicings(specs: dict[str, dict[str, object]]) -> dict[str, dict]:
    """Fill every voicing out to a complete parameter set.

    The literals above are diffs against `_COMMON_DEFAULTS` plus their family's
    defaults, which is what keeps them readable -- but every reader (and the
    cache fingerprint in `samplebank`, which folds this dict) sees whole,
    self-contained dictionaries, so a lookup can never depend on which keys a
    particular voicing happened to spell out.
    """
    out: dict[str, dict] = {}
    for name, spec in specs.items():
        family = spec.get("family", _COMMON_DEFAULTS["family"])
        merged = dict(_COMMON_DEFAULTS)
        merged.update(_STRING_DEFAULTS if family == STRING else _ELECTRIC_DEFAULTS)
        merged.update(spec)
        out[name] = merged
    return out


VOICINGS: dict[str, dict] = _merge_voicings(_VOICING_SPECS)

#: Menu labels, in menu order (the dict order of `VOICINGS`).
VOICING_LABELS: dict[str, str] = {
    "grand": "Grand Piano",
    "upright": "Upright Piano",
    "felt": "Felt Piano",
    "rhodes": "Rhodes (electric)",
    "wurlitzer": "Wurlitzer (electric)",
}

# Per-layer parameters. Almost everything else about the timbre follows from
# `velocity`: partial n is scaled by V**(1 + _VEL_TILT*log2(n)), i.e. the top of
# the spectrum grows much faster than the fundamental, which is what makes a
# hard blow brighter instead of merely louder.
#   velocity   : normalised blow strength V (1.0 = ff)
#   noise_bias : dB added to the mechanical noise -- a pp blow excites the
#                strings far less than it does the action, so the noise sits
#                relatively higher there
_LAYER_PARAMS = {
    "soft": dict(velocity=0.32, noise_bias=4.0),
    "hard": dict(velocity=1.00, noise_bias=0.0),
}

_VEL_TILT = 0.55        # growth of the velocity exponent per partial octave

# ------------------------------------------------------------------ decay laws
_T60_REF_HZ = 261.63    # frequency at which t60_ref_s is quoted (C4)
_T60_MIN = 0.06
_KNEE_AMP = 0.14        # stage-2 weight: the two decay asymptotes cross where
#                         each contributes 10**(-25/20), i.e. a -25 dB knee
_STAGE2_RATIO = 3.0     # stage-2 T60 = 3x stage-1 (polarisation aftersound)

#: The same two numbers for the electric family. A tine's decay is far closer to
#: a single exponential than a string's -- there is no second polarisation to
#: hand energy to -- but it does have a long, quiet tail, so the knee is left in
#: at a tenth of the string's weight.
_KNEE_AMP_ELECTRIC = 0.05
_STAGE2_RATIO_ELECTRIC = 2.2

# A partial is rendered only while it is above `_AMP_FLOOR` of the note's peak
# (-80 dB, far under int16 resolution), and never for more than `_ENV_TRUNC`
# time constants. Without this the bass would spend most of its render time
# writing silence for high partials that die in a fraction of the buffer.
_AMP_FLOOR = 1.0e-4
_ENV_TRUNC = 11.0

# Runaway guard for the partial loops: A0 needs ~340 inharmonic partials to
# reach Nyquist, and no electric voicing is asked for more than 256 harmonics
# (past that the steepest tilt any of them uses is under the amplitude floor).
_MAX_PARTIALS = 512
_MAX_HARMONICS = 256

# Envelope/beating control rate: both are slow (the shortest T60 is 60 ms, the
# fastest rendered unison beat ~6 Hz), so they are evaluated every `_ENV_STEP`
# samples and linearly interpolated. That keeps the per-sample work down to one
# sine per partial.
_ENV_STEP = 32

# Unison strings beat, but only just: past ~3 cents a piano reads as out of
# tune. Companion strings are spread 0.5-2.0 cents.
_DETUNE_MIN_CT = 0.5
_DETUNE_MAX_CT = 2.0
_CENT = 5.7779e-4       # one cent as a frequency ratio offset


def _seed(*parts: object) -> int:
    """Deterministic RNG seed: `hash()` of a str is salted per process."""
    key = "|".join(str(p) for p in parts).encode("utf-8")
    return int.from_bytes(hashlib.blake2b(key, digest_size=8).digest(), "big")


def _voicing(voicing: str) -> dict:
    return VOICINGS.get(voicing, VOICINGS[DEFAULT_VOICING])


def family(voicing: str = DEFAULT_VOICING) -> str:
    """Which engine renders `voicing`: `STRING` or `ELECTRIC`."""
    return str(_voicing(voicing)["family"])


def midi_to_freq(note: int) -> float:
    return 440.0 * 2.0 ** ((note - 69) / 12.0)


def _key_position(note: int) -> float:
    """Where a key sits on the keyboard: 0.0 at A0, 1.0 at C8."""
    return (min(max(int(note), NOTE_MIN), NOTE_MAX) - NOTE_MIN) / (NOTE_MAX - NOTE_MIN)


def note_duration(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """Rendered buffer length in seconds (bass rings far longer than treble).

    `samplebank` validates every cached buffer against this, so it has to stay
    exactly consistent with the length `render_note` returns.
    """
    v = _voicing(voicing)
    bass, treble = float(v["dur_bass_s"]), float(v["dur_treble_s"])
    return bass * (treble / bass) ** _key_position(note)


# ============================================================================
#  Struck strings: grand, upright, felt
# ============================================================================

# Inharmonicity anchors, from published measurements on grands: B spans three
# orders of magnitude and is *not* a single exponential in key number -- the
# wound bass strings are far more flexible for their pitch than the plain steel
# above them, so B is interpolated exponentially between measured anchors.
#   A0-C2 3e-5..5e-5, C4 2.5e-4, C7-C8 1.2e-2..3e-2
_B_NOTES = np.array([21.0, 36.0, 48.0, 60.0, 72.0, 84.0, 96.0, 108.0])
_B_VALUES = np.array([3.0e-5, 5.0e-5, 1.1e-4, 2.5e-4, 8.0e-4, 2.5e-3,
                      1.2e-2, 3.0e-2])
_B_LOG = np.log(_B_VALUES)


def inharmonicity(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """String inharmonicity coefficient B: ~3e-5 in the bass to ~3e-2 at C8.

    The voicing scales it, log-interpolated from `inharm_bass` at A0 to
    `inharm_treble` at C8. That gradient is the point rather than a refinement:
    what makes an upright's bottom octave sound like an upright is that its
    bass strings had to be cut to fit the case, so their partials are stretched
    several times as far as a nine-foot grand's, while its treble -- where the
    speaking lengths are similar -- is barely touched.
    """
    n = float(min(max(int(note), NOTE_MIN), NOTE_MAX))
    v = _voicing(voicing)
    base = float(np.exp(np.interp(n, _B_NOTES, _B_LOG)))
    scale = math.exp(math.log(float(v["inharm_bass"]))
                     + (math.log(float(v["inharm_treble"]))
                        - math.log(float(v["inharm_bass"]))) * _key_position(note))
    return base * scale


# ---------------------------------------------------------- stretch tuning
# No piano is tuned to equal temperament, and `inharmonicity` above is why. A
# tuner does not match fundamental to fundamental -- they match the *partials*
# they can hear beating, partial 2 of the lower note against partial 1 of the
# upper -- and because partial 2 sits sharp of 2*f0, the octaves come out
# stretched. Plot that against equal temperament and you have the Railsback
# curve every tuning meter knows: sharp up top, flat at the bottom, crossing
# zero at the A4 that was set with a fork.
#
# This is not decoration. Two notes an octave apart tuned to an exact 2:1 beat
# at (partial 2 of the lower - partial 1 of the upper). Before this existed the
# model's top octave was 37 Hz out -- not a beat, an audibly wrong octave -- and
# that is the loudest reason a spectrally careful piano still reads as
# "electronic" up there: every note individually right, all of them out of tune
# with each other.
#
# The curve is *derived*, not tabulated. Published Railsback curves belong to
# particular real pianos, with the inharmonicity those pianos happened to have;
# tuning to one of those here would put the partials of *this* model somewhere
# they do not belong. So the widening each octave needs is read straight off
# `inharmonicity`,
#
#     D(n) = 600 * log2((1 + 4B(n)) / (1 + B(n+12)))     cents per octave
#
# and integrated across the keyboard. Two consequences worth knowing:
#
#   * The model already carried part of the curve by accident. `partial_series`
#     puts partial 1 at `f0*sqrt(1+B)`, not at `f0`, so every key was already
#     sounding `600*log2(1+B)` sharp of nominal -- 0.03 cents at A0, 2 at C6, 26
#     at C8. That is most of the treble half of a Railsback curve, and it is why
#     the old tuning got away with it below the top octave.
#   * What comes out is nearly all treble. This model's bass B values are small
#     (3e-5 at A0), so its bass octaves were already beatless and the curve
#     leaves them alone -- where a real piano droops 20-30 cents at A0 because
#     its wound bass strings are far more inharmonic than 3e-5. Adding that
#     droop here would be borrowing another instrument's pathology: it would put
#     the bass out of tune with the middle for no acoustic reason. If the bass
#     is ever to sit where a real one does, the number to change is `_B_VALUES`,
#     and this curve will follow it without being touched.
#
# `_STRETCH_STEP` is a compromise the B table forces. Solving the octave
# constraint exactly -- pitch class by pitch class, so every octave is truly
# beatless -- is possible and was measured: it needs 2.5 cents of ripple between
# adjacent semitones, because `_B_VALUES` does not grow at a constant ratio per
# octave (3.1x, 3.1x, 4.8x, 2.5x across the top four). Melodic unevenness of
# that size is far more audible than the beat it removes, so the rate is
# smoothed over a half-semitone grid instead: perfectly even chromatically,
# octaves beatless to well under a hertz everywhere but the top two.
_STRETCH_STEP = 0.5           # semitones per integration step
_STRETCH_ANCHOR = 69          # A4, whose partial 1 comes out at exactly 440 Hz

_stretch_cache: dict[str, tuple[np.ndarray, np.ndarray]] = {}


def _inharmonicity_at(x: float, voicing: str) -> float:
    """`inharmonicity` at a fractional key position, for the integration below."""
    n = min(max(float(x), float(NOTE_MIN)), float(NOTE_MAX))
    v = _voicing(voicing)
    base = float(np.exp(np.interp(n, _B_NOTES, _B_LOG)))
    pos = (n - NOTE_MIN) / (NOTE_MAX - NOTE_MIN)
    scale = math.exp(math.log(float(v["inharm_bass"]))
                     + (math.log(float(v["inharm_treble"]))
                        - math.log(float(v["inharm_bass"]))) * pos)
    return base * scale


def _stretch_table(voicing: str) -> tuple[np.ndarray, np.ndarray]:
    """`(keys, cents)` of the tuning curve, built once per voicing.

    The rate is quoted for the octave *centred* on each grid point -- D(x-6)/12
    rather than D(x)/12 -- so the top of the keyboard is widened by the octave it
    is the upper half of, not by an octave running off the end of the instrument.
    Getting that wrong is worth 30 cents at C8.
    """
    cached = _stretch_cache.get(voicing)
    if cached is not None:
        return cached

    keys = np.arange(float(NOTE_MIN), NOTE_MAX + 1e-9, _STRETCH_STEP)
    rate = np.empty(keys.size)
    for i, x in enumerate(keys):
        lo = min(max(x - 6.0, float(NOTE_MIN)), float(NOTE_MAX - 12))
        b_lo = _inharmonicity_at(lo, voicing)
        b_hi = _inharmonicity_at(lo + 12.0, voicing)
        rate[i] = 600.0 * math.log2((1.0 + 4.0 * b_lo) / (1.0 + b_hi)) / 12.0

    cents = np.concatenate(([0.0], np.cumsum(
        (rate[1:] + rate[:-1]) * 0.5 * _STRETCH_STEP)))
    # Anchor A4: its *sounding* pitch -- partial 1, the one a fork and a meter
    # agree on -- lands on 440.000, which is a place this model has never
    # actually put it.
    cents = cents - float(np.interp(float(_STRETCH_ANCHOR), keys, cents))
    cents = cents - 600.0 * math.log2(
        1.0 + _inharmonicity_at(float(_STRETCH_ANCHOR), voicing))
    cents = cents * float(_voicing(voicing)["stretch"])

    _stretch_cache[voicing] = (keys, cents)
    return keys, cents


def stretch_cents(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """Cents to shift this key's *nominal* `f0` by, away from equal temperament.

    Nominal, not sounding: `partial_series` builds the series on `f0` and puts
    partial 1 at `f0*sqrt(1+B)`, so this number and the deviation a tuning meter
    would read differ by `600*log2(1+B)` -- from nothing in the bass to 26 cents
    at C8. `railsback_cents` is the one to compare against a meter.
    """
    if family(voicing) != STRING:
        return 0.0     # a tine is not a string, and this curve is not its curve
    keys, cents = _stretch_table(voicing)
    return float(np.interp(float(note), keys, cents))


def railsback_cents(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """Where this key ends up sounding, in cents from equal temperament.

    The curve a tuning meter would draw across the keyboard: `stretch_cents`
    plus the stretch the inharmonic series supplies on its own.
    """
    if family(voicing) != STRING:
        return 0.0
    return (stretch_cents(note, voicing)
            + 600.0 * math.log2(1.0 + inharmonicity(note, voicing)))


def tuned_freq(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """`midi_to_freq` after the tuner has been over it (`stretch_cents`)."""
    return midi_to_freq(note) * 2.0 ** (stretch_cents(note, voicing) / 1200.0)


# Hammer strike position as a fraction of the speaking length: 1/8-1/9 in the
# bass, 1/7 through the middle (which is what keeps the dissonant 7th partial
# weak), ~1/12 at the top where the string is far too short to strike
# proportionally.
_STRIKE_NOTES = np.array([21.0, 36.0, 48.0, 60.0, 72.0, 84.0, 96.0, 108.0])
_STRIKE_DIV = np.array([8.7, 8.2, 7.4, 7.0, 7.6, 9.0, 10.5, 12.0])


def strike_position(note: int, voicing: str = DEFAULT_VOICING) -> float:
    """Hammer contact point as a fraction of the string length."""
    n = float(min(max(int(note), NOTE_MIN), NOTE_MAX))
    return float(np.interp(n, _STRIKE_NOTES, _STRIKE_DIV)) ** -1.0 \
        * float(_voicing(voicing)["strike_scale"])


def unison_count(note: int) -> int:
    """Strings per note: 1 up to E1, 2 up to B2, 3 from C3 up."""
    if note <= 28:      # A0-E1: one wound string
        return 1
    if note <= 47:      # F1-B2: bichords
        return 2
    return 3            # C3-C8: trichords


#: How fast a plate stops radiating below its critical frequency: as f**2, i.e.
#: 12 dB per octave. `rad_corner_hz` is where that sets in for a given board.
_RAD_DB_OCT = 12.0


def _radiation_gain(freq, corner_hz: float = 200.0):
    """Linear radiation efficiency of the board below `corner_hz`.

    A plate radiates ever worse as the wavelength in air outgrows it: below its
    critical frequency the radiation efficiency falls as f**2, i.e. 12
    dB/octave. For a piano soundboard that corner sits a couple of hundred Hz up
    -- which is exactly why A0's fundamental is not its strongest partial, and
    why a model that is flat down to DC sounds like a synthesiser.
    """
    f = np.asarray(freq, dtype=np.float64)
    octaves_below = np.maximum(np.log2(corner_hz / np.maximum(f, 1e-6)), 0.0)
    return 10.0 ** (-_RAD_DB_OCT * octaves_below / 20.0)


# The board radiates through its own modes: the classic low trio near 50/80/120
# Hz plus a broader mid group -- the "wood" of the instrument.
#   (Hz, Q, steady-state gain (linear), resonant gain in the body IR (dB))
# The two gains are separate on purpose: the *steady* peaks of a real radiated
# spectrum are only a few dB (many modes overlap), while a single struck impulse
# rings audibly through the same modes. The IR gains are quoted in dB *above the
# board's direct path*, so the impulse response stays a plausible filter (a few
# dB of colouring) instead of the +60 dB low-frequency monster you get by
# summing decaying sinusoids of equal amplitude and normalising in time.
_BOARD_MODES = (
    (50.0, 8.0, 1.66, 9.0), (80.0, 9.0, 1.75, 11.0),
    (120.0, 8.0, 1.54, 8.0), (215.0, 6.0, 1.80, 6.0),
    (340.0, 5.0, 1.50, 5.0), (700.0, 3.5, 1.25, 3.5),
    (1500.0, 2.5, 1.15, 2.5),
)

# Mechanical noise levels in dB relative to the *reference* tone peak (i.e. to
# a grand's strings, not to the current voicing's), before the voicing's
# `action_db` trim.
_HAMMER_DB = -15.0      # broadband hammer strike, 10-25 ms
_THUMP_DB = -20.0       # key bed, peaking near 60 Hz, 20-40 ms
_DAMPER_DB = -32.0      # damper leaving the string, broadband around 2-4 kHz
_HAMMER_MS = 18.0
_THUMP_MS = 28.0
_DAMPER_MS = 15.0


def _board_response_db(freq: np.ndarray, v: dict) -> np.ndarray:
    """Steady-state soundboard response in dB: modal peaks + radiation limit."""
    f = np.asarray(freq, dtype=np.float64)
    db = 20.0 * np.log10(_radiation_gain(f, float(v["rad_corner_hz"])))
    for f_mode, q, gain, _ir_gain in _BOARD_MODES:
        scale = v["board_low"] if f_mode <= 130.0 else v["board_mid"]
        peak = 1.0 + (gain - 1.0) * scale
        # A bump that reaches `peak` at f_mode and 0 dB far away from it.
        shape = 1.0 / np.sqrt(1.0 + (q * (f / f_mode - f_mode / f)) ** 2)
        db += 20.0 * np.log10(1.0 + (peak - 1.0) * shape)
    return db


def _body_ir(samplerate: int, v: dict, rng: np.random.Generator) -> np.ndarray:
    """Short synthesised soundboard impulse response (modal sum, direct path 1.0).

    Only the impulsive excitation (hammer, key bed, damper) is run through it;
    the strings already carry the board's steady-state response in their partial
    amplitudes, which is far cheaper than convolving an 8 s buffer.

    Each mode is scaled so that its *resonant gain* is the dB figure in
    `_BOARD_MODES`: a decaying sinusoid `a*exp(-t/tau)*sin` has a transfer
    magnitude of `a*tau*samplerate/2` at its own frequency, against 1.0 for the
    unit sample of direct sound. Without that normalisation a 60 ms low mode
    carries ~+60 dB of gain, and every burst -- even a 3 kHz damper hiss --
    comes out of the board as a thud.
    """
    n = int(0.28 * samplerate)
    t = np.arange(n, dtype=np.float32) / samplerate
    ir = np.zeros(n, dtype=np.float32)
    ir[0] = 1.0                                 # direct, unfiltered path (0 dB)
    for f_mode, q, _gain, ir_db in _BOARD_MODES:
        scale = v["board_low"] if f_mode <= 130.0 else v["board_mid"]
        tau = q / (math.pi * f_mode)            # ring time implied by the mode's Q
        amp = (10.0 ** (ir_db * scale / 20.0)) * 2.0 / (tau * samplerate)
        phase = float(rng.uniform(0.0, 2.0 * math.pi))
        ir += (amp * np.exp(-t / tau, dtype=np.float32)
               * np.sin(2.0 * math.pi * f_mode * t + phase)).astype(np.float32)
    return ir.astype(np.float32)


def _shaped_noise(rng: np.random.Generator, n: int, samplerate: int,
                  slope_db_oct: float, corner_hz: float, peak_hz: float = 0.0,
                  q: float = 0.0) -> np.ndarray:
    """White noise shaped in the frequency domain (exact, and cheap when short).

    `slope_db_oct` applies above `corner_hz`; below it the burst is high-passed
    at 12 dB/octave so the noises do not pile up DC. An optional resonance at
    `peak_hz` is what gives the key-bed thump its pitch.
    """
    if n < 8:
        return np.zeros(max(n, 0), dtype=np.float32)
    noise = rng.standard_normal(n)
    spec = np.fft.rfft(noise)
    f = np.maximum(np.fft.rfftfreq(n, 1.0 / samplerate), 1.0)
    mag = 10.0 ** (slope_db_oct * np.maximum(np.log2(f / corner_hz), 0.0) / 20.0)
    mag /= 1.0 + (corner_hz / f) ** 2            # 12 dB/oct high-pass skirt
    if peak_hz > 0.0 and q > 0.0:
        mag *= 1.0 + 6.0 / np.sqrt(1.0 + (q * (f / peak_hz - peak_hz / f)) ** 2)
    out = np.fft.irfft(spec * mag, n).astype(np.float32)
    peak = float(np.max(np.abs(out))) or 1.0
    return (out / peak).astype(np.float32)


def _burst(rng: np.random.Generator, n: int, samplerate: int, length_ms: float,
           slope: float, corner: float, decay_frac: float, attack_ms: float,
           peak_hz: float = 0.0, q: float = 0.0) -> np.ndarray:
    """One shaped, enveloped noise burst -- the shape every knock in here has."""
    m = min(n, max(16, int(length_ms * 1e-3 * samplerate)))
    raw = _shaped_noise(rng, m, samplerate, slope, corner, peak_hz, q)
    tt = np.arange(m, dtype=np.float32) / samplerate
    n_atk = max(2, int(attack_ms * 1e-3 * samplerate))
    env = np.exp(-tt / (decay_frac * length_ms * 1e-3), dtype=np.float32)
    env[:n_atk] *= np.linspace(0.0, 1.0, n_atk, dtype=np.float32) ** 2
    return raw * env


def _fft_convolve(x: np.ndarray, h: np.ndarray) -> np.ndarray:
    """Convolution via FFT -- the excitation is short, so this costs ~1 ms."""
    n_out = x.size + h.size - 1
    n_fft = 1 << int(math.ceil(math.log2(max(n_out, 2))))
    y = np.fft.irfft(np.fft.rfft(x, n_fft) * np.fft.rfft(h, n_fft), n_fft)
    return y[:n_out].astype(np.float32)


def _mechanical_noise(n: int, samplerate: int, v: dict, velocity: float,
                      noise_bias: float, rng: np.random.Generator) -> np.ndarray:
    """Hammer strike + key-bed thump + damper lift, rung through the body.

    Each component is scaled so that its own peak lands exactly on the level it
    is quoted at (`_HAMMER_DB` and friends, relative to a reference tone peak of
    1.0), then the whole layer is trimmed by the voicing's `action_db`. Because
    those levels are absolute, a voicing that turns its strings down -- `felt` --
    would otherwise end up with the action as a co-equal layer; the trim keeps it
    a texture under the tone while `velocity` still moves it.
    """
    ir = _body_ir(samplerate, v, rng)
    body_mix = float(v["body_mix"])
    action_db = float(v["action_db"])   # voicing trim of the whole action layer

    vel_db = 20.0 * math.log10(max(velocity, 1e-3))
    parts = [
        # Hammer felt hitting steel: broadband, 10-25 ms, -15 dB at ff. Its
        # level tracks the blow (V**0.8), i.e. a little more slowly than the
        # string's own fundamental does.
        (_burst(rng, n, samplerate, _HAMMER_MS, -4.0, 900.0, 0.35, 0.4),
         _HAMMER_DB + noise_bias + 0.8 * vel_db),
        # Key bed / action bottoming out: 20-40 ms, peaking near 60 Hz. The
        # spectrum is shaped *around* 60 Hz (low-passed above, high-passed
        # below) rather than high-passed at 180 Hz and then resonated back up.
        (_burst(rng, n, samplerate, _THUMP_MS, -14.0, 55.0, 0.30, 1.2,
                peak_hz=60.0, q=3.5),
         _THUMP_DB + noise_bias + 0.5 * vel_db),
        # The damper leaves the string a few ms before the hammer arrives: a
        # soft broadband hiss peaking 2-4 kHz. (Release-side damper noise is the
        # engine's business, not the sample's.)
        (_burst(rng, n, samplerate, _DAMPER_MS, -9.0, 2800.0, 0.40, 0.6),
         _DAMPER_DB + 0.3 * vel_db),
    ]

    out = np.zeros(n, dtype=np.float32)
    for dry, level_db in parts:
        # The IR carries its own direct path, so `body_mix` cross-fades between
        # the bare mechanical sound and the same sound heard through the board.
        wet = _fft_convolve(dry, ir)
        m = min(n, wet.size)
        mixed = np.float32(body_mix) * wet[:m]
        head = min(m, dry.size)
        mixed[:head] += np.float32(1.0 - body_mix) * dry[:head]
        peak = float(np.max(np.abs(mixed))) or 1.0
        out[:m] += mixed * np.float32(10.0 ** ((level_db + action_db) / 20.0) / peak)
    return out


def partial_series(note: int, voicing: str = DEFAULT_VOICING,
                   samplerate: int = SAMPLE_RATE):
    """Indices, frequencies and launch phases of every audible string partial.

    The series is cut at a *frequency*, never at a partial index: an index cap
    means something different at every pitch -- 48 partials stop A0 at ~1.4 kHz
    and A1 at ~2.9 kHz while C4 still reaches ~17 kHz, so the bottom two octaves
    came out audibly duller than the rest of the instrument.

    `voicing` reaches the series through two numbers only, `inharmonicity` and
    the `stretch` behind `tuned_freq`: the hammer, the board and the dampers are
    all downstream of the string and belong to `partial_amplitudes` and the decay
    law instead. Two voicings that share both (grand and felt) therefore get
    *identical* frequencies and phases, which is what makes them read as one
    instrument played two ways rather than as two different pianos.

    Struck-string voicings only; the electric family has bending modes rather
    than a stretched harmonic series (see `electric_partials`).
    """
    f0 = tuned_freq(note, voicing)
    B = inharmonicity(note, voicing)
    idx = np.arange(1, _MAX_PARTIALS + 1, dtype=np.float64)
    freqs = idx * f0 * np.sqrt(1.0 + B * idx * idx)
    keep = freqs <= samplerate * 0.5 * 0.92
    idx, freqs = idx[keep], freqs[keep]

    # Phases are seeded per *note* (not per layer, not per voicing) so both
    # velocity layers stay phase-coherent and cross-fade cleanly. Phase is random
    # across partials and *shared* by the strings of a unison: give the strings
    # of one choir independent phases and their fundamentals cancel each other
    # out.
    rng = np.random.default_rng(_seed("string", note))
    phases = rng.uniform(0.0, 2.0 * math.pi, size=idx.size)
    # No real string is perfectly regular: a few tenths of a cent of pitch
    # scatter per partial keeps the series from sounding like a drawbar organ.
    freqs = freqs * (1.0 + rng.normal(0.0, 0.3, size=idx.size) * _CENT)
    return idx, freqs, phases


# Floors the strike comb is blended against, i.e. how much of a comb null the
# bridge and the board radiate anyway. The fundamental gets the generous one:
# a nulled fundamental sounds thin and nasal.
_COMB_FLOOR_F0 = 0.55
_COMB_FLOOR = 0.14


def partial_amplitudes(idx: np.ndarray, freqs: np.ndarray, note: int, layer: str,
                       voicing: str = DEFAULT_VOICING) -> np.ndarray:
    """Linear amplitude of every string partial at launch, peak-normalised to 1.

    Kept entirely in dB so that each acoustic term stays traceable.
    """
    v = _voicing(voicing)
    velocity = float(_LAYER_PARAMS[layer]["velocity"])
    amp_db = v["tilt_db_oct"] * np.log2(idx)                    # string spectrum
    amp_db += v["hf_db_oct"] * np.maximum(np.log2(freqs / v["hf_corner_hz"]), 0.0)
    # Hammer comb: |sin(pi*n*p)| suppresses every (1/p)-th partial. The raw comb
    # also nearly nulls the fundamental, which sounds thin and nasal -- real
    # instruments get it back through bridge/soundboard cross-radiation, so the
    # nulls are filled to a floor, generously so for the fundamental.
    comb = np.abs(np.sin(math.pi * idx * strike_position(note, voicing)))
    floor = np.where(idx == 1.0, _COMB_FLOOR_F0, _COMB_FLOOR)
    amp_db += 20.0 * np.log10(np.sqrt(floor ** 2 + (1.0 - floor ** 2) * comb ** 2))
    # Velocity is timbre, not just level: A_n ~ V**(1 + _VEL_TILT*log2(n)).
    amp_db += 20.0 * math.log10(max(velocity, 1e-4)) * (1.0 + _VEL_TILT * np.log2(idx))
    # Body: modal peaks plus the low-frequency radiation limit.
    amp_db += _board_response_db(freqs, v)
    # +-1.2 dB of amplitude scatter on the overtones: the ear reads a perfectly
    # smooth series as synthetic (and no real hammer combs ideally either). The
    # fundamental is left alone -- its level is what the board's radiation term
    # above decides, and it is the reference every other partial is heard
    # against.
    rng = np.random.default_rng(_seed("scatter", note))
    amp_db[1:] = amp_db[1:] + rng.normal(0.0, 1.2, size=idx.size - 1)
    # Voicing emphasis of the fundamental (felt/moderator), weighted by how well
    # the board can radiate it: no voicing can resurrect A0's 27.5 Hz.
    amp_db[0] += v["fund_db"] * float(
        _radiation_gain(freqs[0], float(v["rad_corner_hz"])))

    amps = 10.0 ** (amp_db / 20.0)
    return amps / float(amps.max())


def unison_choir(note: int, voicing: str = DEFAULT_VOICING):
    """Detune ratios and gains of the strings struck by one hammer.

    Companion strings are detuned 0.5-2.0 cents (past ~3 the piano reads as out
    of tune) and *share* the launch phase -- one hammer starts them together.
    A single wound bass string still beats: its vertical and horizontal
    polarisations sit a few tenths of a cent apart.
    """
    n_strings = unison_count(note)
    rng = np.random.default_rng(_seed("unison", note))
    cents = [0.0]
    gains = [1.0 / n_strings] * n_strings
    for j in range(1, n_strings):
        sign = -1.0 if j % 2 else 1.0
        cents.append(sign * float(rng.uniform(_DETUNE_MIN_CT, _DETUNE_MAX_CT)))
    if n_strings < 3:                       # polarisation partner, bass strings
        cents.append(float(rng.uniform(0.15, 0.45)))
        gains.append(0.4 / n_strings)
    detune = np.array([2.0 ** (c / 1200.0) - 1.0 for c in cents])
    return detune, np.array(gains)


# ============================================================================
#  Struck bars behind a pickup: rhodes, wurlitzer
# ============================================================================

def electric_partials(note: int, layer: str, voicing: str,
                      samplerate: int = SAMPLE_RATE):
    """Every component of one tine/reed: `(freqs, amps, t60, atk_scale, phases)`.

    Two populations, concatenated, because they behave nothing like each other:

      * the **harmonic series** the pickup makes out of a nearly sinusoidal
        swing. Harmonic n comes from the n-th order term of the pickup's
        transfer, so its amplitude goes as the n-th power of the excursion --
        which is exactly why the T60 ~ 1/f law below makes harmonic n decay n
        times faster, and why an electric piano gets *purer* as it rings.
      * the **bending modes** of the bar itself, at 1 : 6.267 : 17.55 : 34.39 for
        a clamped-free tine (`bar_ratios`). These are the bark. They are steeply
        velocity-dependent, they are gone in a few hundred milliseconds, and
        they are the whole reason a Rhodes patch built from a filtered sawtooth
        never sounds like one.

    Amplitudes are peak-normalised to 1.0, like `partial_amplitudes`.
    """
    v = _voicing(voicing)
    velocity = float(_LAYER_PARAMS[layer]["velocity"])
    f0 = midi_to_freq(note)
    nyquist = samplerate * 0.5 * 0.92
    rng = np.random.default_rng(_seed("tine", note))

    # ---- harmonics of the fundamental -------------------------------------
    n_harm = int(min(_MAX_HARMONICS, max(1.0, nyquist / f0)))
    idx = np.arange(1, n_harm + 1, dtype=np.float64)
    h_freqs = idx * f0
    h_db = float(v["tilt_db_oct"]) * np.log2(idx)
    h_db += float(v["hf_db_oct"]) * np.maximum(
        np.log2(h_freqs / float(v["hf_corner_hz"])), 0.0)
    # Odd harmonics lead on a reed (a flat bar swinging in a symmetric gap is
    # driven by an odd non-linearity), even ones on a tine sitting off-centre in
    # its magnetic field. This one pair of numbers is most of what separates a
    # hollow Wurlitzer from a glassy Rhodes.
    h_db += np.where((idx % 2.0) == 1.0, float(v["odd_db"]), float(v["even_db"]))
    h_db[0] = 0.0                       # the fundamental is the reference
    # Velocity is timbre: the harmonics *are* the non-linearity, so they grow
    # with the blow far faster than the fundamental does.
    h_db += 20.0 * math.log10(max(velocity, 1e-4)) * _VEL_TILT * np.log2(idx)
    h_db[1:] += rng.normal(0.0, 0.9, size=max(idx.size - 1, 0))
    h_t60 = float(v["t60_ref_s"]) * (_T60_REF_HZ / h_freqs) ** float(v["t60_slope"])
    h_t60 = h_t60 * np.minimum(float(v["hf_corner_hz"]) / h_freqs, 1.0) ** float(
        v["hf_damp"])
    h_atk = np.ones(idx.size)

    # ---- bending modes of the bar -----------------------------------------
    ratios = np.asarray(v["bar_ratios"], dtype=np.float64)
    scatter = 1.0 + rng.normal(0.0, float(v["bar_detune_ct"]), size=ratios.size) * _CENT
    b_freqs = f0 * ratios * scatter
    b_db = float(v["bar_db"]) + float(v["bar_tilt_db"]) * np.arange(ratios.size)
    b_db += 20.0 * math.log10(max(velocity, 1e-4)) * (float(v["bar_vel_exp"]) - 1.0)
    # A 1 kHz mode rings for `bar_t60_s`; higher ones die faster, but nothing
    # like as fast as 1/f -- the bar's losses are internal, not radiative.
    b_t60 = float(v["bar_t60_s"]) * np.clip((1000.0 / b_freqs) ** 0.40, 0.45, 2.2)
    # The bell is the first thing you hear: the bar's own modes are struck
    # directly, while the pickup's harmonics have to wait for a swing to bend.
    b_atk = np.full(ratios.size, 0.35)

    freqs = np.concatenate((h_freqs, b_freqs))
    amp_db = np.concatenate((h_db, b_db))
    t60 = np.concatenate((h_t60, b_t60))
    atk_scale = np.concatenate((h_atk, b_atk))

    keep = freqs <= nyquist
    freqs, amp_db, t60, atk_scale = (freqs[keep], amp_db[keep], t60[keep],
                                     atk_scale[keep])
    amps = 10.0 ** (amp_db / 20.0)
    amps = amps / float(amps.max()) if amps.size else amps
    t60 = np.clip(t60, _T60_MIN, float(v["t60_max_s"]))
    phases = np.random.default_rng(_seed("tine-phase", note)).uniform(
        0.0, 2.0 * math.pi, size=freqs.size)
    return freqs, amps, t60, atk_scale, phases


def electric_pair(note: int, voicing: str = DEFAULT_VOICING):
    """Detune ratios and gains of the bar and the partner it beats against.

    A Rhodes tine is one arm of an asymmetric tuning fork -- the tonebar beside
    it is the other, tuned to the same pitch and never quite reaching it -- so
    every note breathes at a fraction of a hertz. A Wurlitzer reed has no such
    partner and is given only the little the damper felt and the reed's own two
    polarisations provide.
    """
    v = _voicing(voicing)
    rng = np.random.default_rng(_seed("pair", note))
    cents = float(v["beat_ct"]) * float(rng.uniform(0.6, 1.5))
    gain = float(v["beat_gain"])
    detune = np.array([0.0, 2.0 ** (cents / 1200.0) - 1.0])
    gains = np.array([1.0, gain]) / (1.0 + gain)
    return detune, gains


def _knock(n: int, samplerate: int, v: dict, velocity: float, noise_bias: float,
           rng: np.random.Generator) -> np.ndarray:
    """The mechanical noise of an electric piano action.

    Deliberately not `_mechanical_noise`: there is no soundboard to ring, and
    what the pickup hears of the action is a fraction of what the room does. Two
    bursts only -- the hammer tip arriving on the bar (short, bright, and the
    Wurlitzer's harder tip makes it brighter still) and the key bed under it --
    at the voicing's `knock_db`, trimmed by `action_db` like every other action
    layer.
    """
    vel_db = 20.0 * math.log10(max(velocity, 1e-3))
    level = float(v["knock_db"]) + float(v["action_db"])
    parts = [
        (_burst(rng, n, samplerate, 9.0, -5.0, 1600.0, 0.30, 0.25),
         level + noise_bias + 0.9 * vel_db),
        (_burst(rng, n, samplerate, 26.0, -13.0, 70.0, 0.30, 1.0,
                peak_hz=85.0, q=3.0),
         level - 4.0 + noise_bias + 0.5 * vel_db),
    ]
    out = np.zeros(n, dtype=np.float32)
    for dry, level_db in parts:
        m = min(n, dry.size)
        peak = float(np.max(np.abs(dry[:m]))) or 1.0
        out[:m] += dry[:m] * np.float32(10.0 ** (level_db / 20.0) / peak)
    return out


def _dc_block(buf: np.ndarray, samplerate: int, corner_hz: float = 22.0) -> None:
    """Remove the slowly varying offset a `x**2` term leaves behind, in place.

    The asymmetric half of `_pickup` is what puts even harmonics into the tone,
    and an even non-linearity necessarily produces a DC term as well -- one that
    follows the note's envelope, so it is not a constant that could simply be
    subtracted. A sliding mean is the whole filter: exact, one pass, and it costs
    a `cumsum` rather than the per-sample recursion a one-pole would need in
    Python. The window is centred, so the tone is not delayed against the knock
    that is mixed in after it.
    """
    n = buf.size
    width = max(4, int(samplerate / max(corner_hz, 1.0)))
    if n <= width:
        buf -= np.float32(buf.mean())
        return
    lead = width // 2
    ext = np.concatenate((np.full(lead, buf[0], dtype=np.float64),
                          buf.astype(np.float64),
                          np.full(width - lead, buf[-1], dtype=np.float64)))
    cum = np.concatenate(([0.0], np.cumsum(ext)))
    buf -= ((cum[width:width + n] - cum[:n]) / width).astype(np.float32)


def _soft_lowpass(buf: np.ndarray, passes: int) -> None:
    """`passes` of a 3-tap (1, 2, 1)/4 smoother, in place.

    The cheapest honest stand-in for everything downstream of the bar: a pickup
    with inductance, a passive tone control, a preamp. One pass is -3.9 dB at
    8 kHz and a zero at Nyquist, which is roughly where a Rhodes gives up; two
    is the darker, boxier Wurlitzer.
    """
    for _ in range(int(passes)):
        buf[1:-1] = 0.25 * buf[:-2] + 0.5 * buf[1:-1] + 0.25 * buf[2:]


def _pickup(buf: np.ndarray, asym: float, drive: float) -> None:
    """The pickup's non-linear view of the bar, in place. `buf` peaks near 1.0.

    Two terms, in the order the electronics apply them:

      * `asym` -- the field (Rhodes) or the gap capacitance (Wurlitzer) is not
        symmetric about the bar's rest position, so a swing towards the pickup
        is not the mirror of a swing away. `x + a*x**2` is the first term of
        that expansion: it makes even harmonics, strongest at the attack and
        fading as the note decays, which is the "bloom" of an electric piano.
      * `drive` -- everything past that saturates. Gentle on a Rhodes; on a
        Wurlitzer, whose electrostatic pickup works across a gap of a few
        thousandths of an inch at 170 V, it is the bark itself.

    Both are scaled by the caller for velocity, because the buffer has already
    been normalised and a pp blow must not saturate like a ff one.
    """
    if asym:
        buf += np.float32(asym) * buf * buf
    if drive:
        k = float(drive)
        np.tanh(buf * np.float32(k), out=buf)
        buf *= np.float32(1.0 / math.tanh(k))


# ============================================================================
#  Shared summation kernel
# ============================================================================

def _sum_partials(n_pad: int, samplerate: int, freqs, amps, tau1, tau2, knee,
                  tau_atk, phases, detune, gains) -> np.ndarray:
    """Add up every partial: two-stage decay, contact attack, detuned partners.

    One kernel for both families -- the arithmetic of "a few hundred decaying,
    slightly detuned sinusoids" does not care whether the thing vibrating is a
    string or a tine, and keeping two copies of it was two places for a rounding
    bug to hide.

    Everything slow -- the envelope, the beat between detuned partners -- is
    evaluated every `_ENV_STEP` samples and expanded by linear interpolation, so
    the per-sample cost is one `sin` per partial and nothing else. Each partial
    is rendered only for as long as it is above `_AMP_FLOOR`; past that there is
    nothing left to write but silence.
    """
    t = np.arange(n_pad, dtype=np.float32) / samplerate
    n_ctrl = n_pad // _ENV_STEP + 1
    t_ctrl = np.arange(n_ctrl, dtype=np.float64) * (_ENV_STEP / samplerate)
    ramp = np.linspace(0.0, 1.0, _ENV_STEP, endpoint=False, dtype=np.float32)
    dur = n_pad / samplerate

    # How long each partial stays audible: whichever of the two decay stages is
    # still above the floor last. Taking the maximum -- rather than assuming the
    # slow stage always wins, which it does not once a partial is quiet enough
    # that the slow stage starts under the floor -- is what stopped this
    # discarding audible partials outright, and is what keeps it correct for a
    # `knee` of zero, which is what a bar's bending modes ask for.
    knee = np.broadcast_to(np.asarray(knee, dtype=np.float64), amps.shape)
    live1 = np.log(np.maximum((1.0 - knee) * amps / _AMP_FLOOR, 1.0 + 1e-9))
    live2 = np.log(np.maximum(knee * amps / _AMP_FLOOR, 1.0 + 1e-9))
    lengths = np.minimum(np.maximum(tau1 * np.minimum(live1, _ENV_TRUNC),
                                    tau2 * np.minimum(live2, _ENV_TRUNC)), dur)
    ctrl_len = np.minimum((lengths * samplerate / _ENV_STEP).astype(np.int64) + 2,
                          n_ctrl)

    out = np.zeros(n_pad, dtype=np.float32)
    phase_buf = np.empty(n_pad, dtype=np.float32)
    sig_buf = np.empty(n_pad, dtype=np.float32)
    env_buf = np.empty(n_pad, dtype=np.float32)
    two_pi = 2.0 * math.pi

    for i in range(amps.size):
        amp = float(amps[i])
        if amp < _AMP_FLOOR:
            continue
        n_ctrl_i = int(ctrl_len[i])
        m = min((n_ctrl_i - 1) * _ENV_STEP, n_pad)
        if m < _ENV_STEP:
            continue
        tc = t_ctrl[:n_ctrl_i]

        # Two-stage decay: a fast initial fall into a slower aftersound -- on a
        # string, the audible trace of energy crossing from the vertical to the
        # horizontal polarisation.
        k = float(knee[i])
        env_c = ((1.0 - k) * np.exp(-tc / tau1[i]) + k * np.exp(-tc / tau2[i]))
        env_c *= 1.0 - np.exp(-tc / tau_atk[i])
        env_c *= amp

        f = float(freqs[i])
        # Exact amplitude of the detuned pair/choir, evaluated at the control
        # rate: sum_j g_j*sin(w*(1+d_j)*t + phi) is |sum_j g_j*e^(i*w*d_j*t)|
        # times a sine at w -- so the partners cost nothing at audio rate, and
        # only the residual slow phase wobble is dropped. All of them share `phi`
        # (one hammer starts them together; give them independent phases and
        # their fundamentals cancel).
        w = two_pi * f
        re = np.zeros(n_ctrl_i)
        im = np.zeros(n_ctrl_i)
        for g, d in zip(gains, detune):
            if d == 0.0:
                re += g
                continue
            ang = (w * d) * tc
            re += g * np.cos(ang)
            im += g * np.sin(ang)
        env_c = env_c * np.sqrt(re * re + im * im)

        # Expand the control envelope to audio rate: linear between two control
        # points, done as a reshape rather than an interpolation.
        blocks = m // _ENV_STEP
        env_view = env_buf[:m].reshape(blocks, _ENV_STEP)
        base = env_c[:blocks].astype(np.float32)
        delta = (env_c[1:blocks + 1] - env_c[:blocks]).astype(np.float32)
        np.multiply(delta[:, None], ramp[None, :], out=env_view)
        env_view += base[:, None]

        np.multiply(t[:m], np.float32(w), out=phase_buf[:m])
        np.add(phase_buf[:m], np.float32(phases[i]), out=phase_buf[:m])
        np.sin(phase_buf[:m], out=sig_buf[:m])
        np.multiply(sig_buf[:m], env_buf[:m], out=sig_buf[:m])
        np.add(out[:m], sig_buf[:m], out=out[:m])
    return out


def _padded_length(n_samples: int) -> int:
    """`n_samples` rounded up to a whole number of control blocks, plus one.

    The scratch buffers are sized to this so the envelope can be expanded with a
    reshape instead of an interpolation.
    """
    return (n_samples // _ENV_STEP + 2) * _ENV_STEP


def _finish(buf: np.ndarray, n_samples: int) -> np.ndarray:
    """Tail fade and peak normalisation -- the last two steps of every render.

    No de-click ramp is needed at the head: every partial rises from zero through
    its attack time constant, and each noise burst has its own attack.
    """
    n_fade = max(64, int(n_samples * 0.06))
    buf[-n_fade:] *= np.linspace(1.0, 0.0, n_fade, dtype=np.float32)
    peak = float(np.max(np.abs(buf))) or 1.0
    return (buf * (0.98 / peak)).astype(np.float32)


# ============================================================================
#  Render
# ============================================================================

def _render_string(note: int, layer: str, voicing: str,
                   samplerate: int) -> np.ndarray:
    v = _voicing(voicing)
    lp = _LAYER_PARAMS[layer]
    velocity = float(lp["velocity"])
    n_samples = int(note_duration(note, voicing) * samplerate)
    n_pad = _padded_length(n_samples)

    idx, freqs, phases = partial_series(note, voicing, samplerate)
    if idx.size == 0:
        return np.zeros(n_samples, dtype=np.float32)
    amps = partial_amplitudes(idx, freqs, note, layer, voicing)

    # T60 falls as 1/f (air and internal losses), with an extra steepening above
    # the voicing's corner -- a felt strip mostly eats the top of the spectrum.
    t60 = float(v["t60_ref_s"]) * (_T60_REF_HZ / freqs) ** float(v["t60_slope"])
    t60 = t60 * np.minimum(float(v["hf_corner_hz"]) / freqs, 1.0) ** float(v["hf_damp"])
    tau1 = np.clip(t60, _T60_MIN, float(v["t60_max_s"])) / 6.9078
    tau2 = tau1 * _STAGE2_RATIO
    # Hammer contact rounds the attack; the top of the spectrum still arrives
    # sooner than the bottom, and a soft blow keeps the hammer on the string for
    # longer.
    tau_atk = (float(v["attack_ms"]) * 1e-3
               * np.clip((300.0 / freqs) ** 0.20, 0.45, 1.6)
               * (1.0 / max(velocity, 0.05)) ** 0.15)

    detune, gains = unison_choir(note, voicing)
    out = _sum_partials(n_pad, samplerate, freqs, amps, tau1, tau2, _KNEE_AMP,
                        tau_atk, phases, detune, gains)

    buf = out[:n_samples]
    peak = float(np.max(np.abs(buf))) or 1.0
    buf *= np.float32(float(v["tone_gain"]) / peak)   # reference tone peak = 1.0

    nrng = np.random.default_rng(_seed("noise", note, layer, voicing))
    buf += _mechanical_noise(n_samples, samplerate, v, velocity,
                             float(lp["noise_bias"]), nrng)
    return _finish(buf, n_samples)


def _render_electric(note: int, layer: str, voicing: str,
                     samplerate: int) -> np.ndarray:
    v = _voicing(voicing)
    lp = _LAYER_PARAMS[layer]
    velocity = float(lp["velocity"])
    n_samples = int(note_duration(note, voicing) * samplerate)
    n_pad = _padded_length(n_samples)

    freqs, amps, t60, atk_scale, phases = electric_partials(note, layer, voicing,
                                                            samplerate)
    if amps.size == 0:
        return np.zeros(n_samples, dtype=np.float32)

    tau1 = t60 / 6.9078
    tau2 = tau1 * _STAGE2_RATIO_ELECTRIC
    # The bending modes are struck; the harmonics have to wait for the swing to
    # develop, and a soft blow keeps the tip on the bar for longer.
    tau_atk = (float(v["attack_ms"]) * 1e-3 * atk_scale
               * np.clip((300.0 / freqs) ** 0.20, 0.35, 1.8)
               * (1.0 / max(velocity, 0.05)) ** 0.12)

    detune, gains = electric_pair(note, voicing)
    out = _sum_partials(n_pad, samplerate, freqs, amps, tau1, tau2,
                        _KNEE_AMP_ELECTRIC, tau_atk, phases, detune, gains)

    buf = out[:n_samples]
    peak = float(np.max(np.abs(buf))) or 1.0
    buf *= np.float32(float(v["tone_gain"]) / peak)   # reference tone peak = 1.0

    # The pickup sees an excursion, not a level: a pp blow bends the field far
    # less than a ff one, and the buffer above has been normalised, so velocity
    # has to be put back before the non-linearity is applied.
    swing = max(velocity, 0.02) ** 0.7
    _pickup(buf, float(v["pickup_asym"]) * swing, float(v["pickup_drive"]) * swing)
    _dc_block(buf, samplerate)
    _soft_lowpass(buf, int(v["hf_taps"]))

    nrng = np.random.default_rng(_seed("knock", note, layer, voicing))
    buf += _knock(n_samples, samplerate, v, velocity, float(lp["noise_bias"]), nrng)
    return _finish(buf, n_samples)


def render_note(note: int, layer: str, voicing: str = DEFAULT_VOICING,
                samplerate: int = SAMPLE_RATE) -> np.ndarray:
    """Render one note/velocity-layer as mono float32, peak-normalised.

    Dispatches on the voicing's family; an unknown voicing renders as the
    default, which is also how `samplebank` and `config` treat one.
    """
    if family(voicing) == ELECTRIC:
        return _render_electric(note, layer, voicing, samplerate)
    return _render_string(note, layer, voicing, samplerate)


# Per-note playback gain so the keyboard sounds balanced end to end, times the
# voicing's make-up gain. A struck string loses its top octaves fast and needs
# them held back; an electric piano's pickup output is far more even, so its
# curve is flatter.
_GAIN_NOTES = np.array([21, 33, 45, 60, 72, 84, 96, 108], dtype=np.float32)
_GAIN_VALS = {
    STRING: np.array([0.95, 1.00, 1.00, 1.00, 0.92, 0.82, 0.70, 0.58],
                     dtype=np.float32),
    ELECTRIC: np.array([0.98, 1.00, 1.00, 1.00, 0.96, 0.90, 0.82, 0.74],
                       dtype=np.float32),
}


def note_gain(note: int, voicing: str = DEFAULT_VOICING) -> float:
    v = _voicing(voicing)
    return (float(np.interp(note, _GAIN_NOTES, _GAIN_VALS[str(v["family"])]))
            * float(v["gain"]))
